name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Dir
      run: ls -n /Applications/ | grep Xcode*
    - name: Choose Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_13.1.app/Contents/Developer
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
